auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title

title:            zhuqs.com
url:              http://vivzqs.github.com
feed:             /atom.xml
author:
    name:         zhuqs
    
description:      "zhuqs's Blog"


copyright:
    - Design by <a href="http://beiyuu.com/about" title="BeiYuu" target="_blank">BeiYuu</a> &copy; 2013
